GET  http://localhost:3333

###
POST  http://localhost:3333/api/links
content-type: application/json

{
    "code": "fogete",
    "url": "https://www.rocketseat.com.br/"
}

###
GET  http://localhost:3333/api/links

###
GET  http://localhost:3333/rocktseat

###
GET  http://localhost:3333/api/metrics

